### ISSUE TITLE
Step does not post comments to tasks

### ISSUE THREAD

**Issue by marcelskotnicki** [DroidsOnRoids/bitrise_step_build_info_jira_comment#2]
Hi, thanks for reading this message.

I am writing to you as I cannot understand how to make your step work. I think I got everything I need, but there is simply something wrong and the output is poor. I'd like to attach few screens of step configuration and Bitrise output logs.
Is there anything you can do to help me out? Thanks in advance.

Attachments 1&2: Step inputs  
![image](https://user-images.githubusercontent.com/19238243/91171118-3da98400-e6da-11ea-9692-f16cb4c6f473.png)
![image](https://user-images.githubusercontent.com/19238243/91171159-55810800-e6da-11ea-9914-e627b0e31eb0.png)
(Passing _Jira user_ and _Jira user token_ did not make any changes)

Attachment 3: Bitrise logs concerning _jira-comments_ step
![image](https://user-images.githubusercontent.com/19238243/91170881-d55aa280-e6d9-11ea-8bb4-231e767f20db.png)

**Comment by maqoo** [comment]
Hi mskx42!

Your commit message should contain something like ‘MOH-123’ for this to work which corresponds to JIRA ticket. Once this information is extracted, the step will try to send info as a comment to this task. If there will be more than one task specified, then all of the tasks will be extracted from commit messages and will be used to post a comment with build info.

Cheers!

Kind Regards / Pozdrawiam, Maciej Stramski

**Comment by marcelskotnicki** [comment]
Hi @maqoo, thanks for the reply!

My commit message did include task number (like `MOH-123`), but no success. Is there something more I can do?
By the way, do you support various tasks like `MOH-123` and `HOM-987` in the same commit message?

Cheers

**Comment by maqoo** [comment]
> Hi @maqoo, thanks for the reply!
> 
> My commit message did include task number (like `MOH-123`), but no success. Is there something more I can do?

But I can see from the screenshot of bitrise log you provided the commit messages do not have the jira tasks specified. There should e.g. "MOH-123 remove crashlytics mappings upload". This would be a valid commit message from which the task can be extracted.

> By the way, do you support various tasks like `MOH-123` and `HOM-987` in the same commit message?

Sorry - only one project identifier is supported here. Feel free to contribute if you need additional functionality.

**Comment by marcelskotnicki** [comment]
> But I can see from the screenshot of bitrise log you provided the commit messages do not have the jira tasks specified. There should e.g. "MOH-123 remove crashlytics mappings upload". This would be a valid commit message from which the task can be extracted.

The exact commit message was:

> remove crashlytics mappings upload
> 
> MOH-860

And about various tasks

> Sorry - only one project identifier is supported here. Feel free to contribute if you need additional functionality.

We'll see what we can do 😄

**Comment by maqoo** [comment]
> remove crashlytics mappings upload
> 
> MOH-860

Seems like a newline commit message problem. I think this can be a bug in the script. Please try changing the commit message to include the jira ticket reference name in the first line.

**Comment by marcelskotnicki** [comment]
That was also done in another commit with no success.
I'll try to do it once again and be back with you in few minutes.

**Comment by marcelskotnicki** [comment]
Unfortunately, adding task number to commit message did not work and ended up with 401. 
According to this step, _Jira user_ and _Jira user token_ are not required.

Attachment 1: Failed bitrise logs
![image](https://user-images.githubusercontent.com/19238243/91190525-f4fec480-e6f3-11ea-8b3a-4b4da747a674.png)

Nevertheless, after adding _Jira user_ and _Jira user token_ this process finally succeed! 🚀 
It was important for me to add task number to **commit (merge) message**, not **pull request description**.

Attachment 2: Successful bitrise logs
![image](https://user-images.githubusercontent.com/19238243/91193218-24630080-e6f7-11ea-8f21-2a44cebe7589.png)

Thanks for your help!
