### ISSUE TITLE
fatal: ..: '..' is outside repository

### ISSUE THREAD

**Issue by jmonroe** [DroidsOnRoids/bitrise_step_build_info_jira_comment#6]
When using this step I began getting failures recently with the following error

`fatal: ..: '..' is outside repository at '/Users/vagrant/git'`

Nothing has changed in our configuration or message.  I have confirmed that the necessary parameters are all correct.  I'm not sure if this is due to a change in how bitrise is executing the script, but wanted to report.

**Comment by koral--** [comment]
With the amount of information you provided now I can do nothing.
Share a reproducer project.

**Comment by jmonroe** [comment]
Following up on my own issue since a co-worker ran into it on their project and found this issue.  The solution was to update bitrise to use a clone depth of -1 to cause it to do a deep checkout.

**Comment by koral--** [comment]
OK, now it is clear.
`git log` invocation returned an empty string.
There's a similar issue here: #7
I'll consider checking the git history upfront and printing some more user-friendly message.
