### ISSUE TITLE
failing JIRA step 

### ISSUE THREAD

**Issue by lrodriguez2022** [DroidsOnRoids/bitrise_step_build_info_jira_comment#7]
fatal: ..: '..' is outside repository at '/bitrise/src'

**Comment by koral--** [comment]
It seems that the git invocation evaluated to an empty string:
https://github.com/DroidsOnRoids/bitrise_step_build_info_jira_comment/blob/master/step.sh#L12
For example you have no commits in the repository.

With this amount of information you provided it is impossible to do anything.

**Comment by lrodriguez2022** [comment]
Thank you for your reply. No commits present seems to be the case. What would be the easiest way to run only if there are commits present? (this way, the whole step won't fail, but will get omitted)

**Comment by koral--** [comment]
You can use `run_if` property for that.
For example if there is no `BITRISE_GIT_COMMIT` env var set in those cases:
`{{getenv "BITRISE_GIT_COMMIT" | ne ""}}`
![image](https://github.com/DroidsOnRoids/bitrise_step_build_info_jira_comment/assets/3340954/ecb89956-0c27-4bc7-8ff3-9f9cc69fdd61)

More info in bitrise docs:
https://devcenter.bitrise.io/en/steps-and-workflows/introduction-to-steps/enabling-or-disabling-a-step-conditionally.html
